#cloud-config
ssh_import_id: ['lp:pgdg99']
ssh_authorized_keys: [ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJarMH7ITZbBSf6iA8RzneJfgDQt3H9pDs1lm+RjmAXq pablo.degreiff@canonical.com]
ssh_genkeytypes: [ed25519]

write_files:
- path: /etc/netplan/60-lxdbr0.yaml
  permissions: '0600'
  content: |
    network:
      version: 2
      bridges:
        lxdbr0:
          addresses: [10.10.20.1/24]
          parameters:
            stp: false
            forward-delay: 0

- path: /etc/sysctl.d/99-maas-nat.conf
  content: |
    net.ipv4.ip_forward=1

- path: /etc/profile.d/maas-login.sh
  permissions: '0644'
  content: |
    if [ "$USER" = "ubuntu" ] && command -v maas >/dev/null 2>&1; then
        ADMIN_USER="admin"
        maas login $ADMIN_USER 'http://localhost:5240/MAAS/' $(sudo maas apikey --username $ADMIN_USER) >/dev/null 2>&1
    fi

- path: /etc/profile.d/default-editor.sh
  permissions: '0644'
  content: |
    export EDITOR=nvim

- path: /etc/sudoers.d/keep-editor
  permissions: '0440'
  content: |
    Defaults env_keep += "EDITOR"

lxd:
  preseed: |
    config:
      core.https_address: '[::]:8444'
    storage_pools:
    - config:
        size: 160GB
      description: ""
      name: default
      driver: zfs 
    profiles:
    - config: {}
      description: ""
      devices:
        root:
          path: /
          pool: default
          type: disk
      name: default
    projects: []
    cluster: null

apt:
  sources:
    source1:
      source: ppa:maas/3.6
      
snap:
  commands:
  - snap install juju

packages:
  - git
  - neovim
  - pollinate
  - jq
  - iptables-persistent

package_update: true
package_upgrade: true
package_reboot_if_required: true

hostname: server
create_hostname_file: true
fqdn: server.landscape.com
prefer_fqdn_over_hostname: true

timezone: America/Bogota

random_seed:
  command: [pollinate]
  command_required: true
  file: /dev/urandom

runcmd:

# Export variables
- echo "\n\n-------- Exporting variables... --------\n"

- export SSH_KEY=lp:pgdg99

- export ADMIN_USER=admin
- export ADMIN_PASS=admin
- export ADMIN_EMAIL=admin@mail.com

- export GATEWAY=10.10.20.1
- export SUBNET=10.10.20.0/24
- export LXD_CERT="/root/lxd-local.crt"
- export LXD_KEY="/root/lxd-local.key"

- export MAAS_PROJECT_NAME=$(hostname)
- export MAAS_DNS=8.8.8.8
- export MAAS_RESERVED_IP_START=10.10.20.200
- export MAAS_RESERVED_IP_END=10.10.20.254

- export JUJU_CONTROLLER_CPU=2
- export JUJU_CONTROLLER_RAM=8192
- export JUJU_CONTROLLER_DISK=20

- export NODE_CPU=3
- export NODE_RAM=8192
- export NODE_MAIN_DISK=40

- export CLIENT_CPU=2
- export CLIENT_RAM=4096
- export CLIENT_MAIN_DISK=10
- export CLIENT_BASE=ubuntu@22.04
- export CLIENT_ACCOUNT_NAME=standalone
- export CLIENT_COMPUTER_NAME=client

- export HAPROXY_VERSION=latest/stable
- export POSTGRESQL_VERSION=14/stable
- export RABBITMQ_VERSION=3.9/stable
- export LANDSCAPE_SERVER_VERSION=latest/stable
- export LANDSCAPE_CLIENT_VERSION=latest/stable

- export IP_ADDRESS=$(hostname -I | awk '{print $1}')
- export INTERFACE=$(ip -j route show default | jq -r '.[].dev')
- export LANDSCAPE_FQDN=$(hostname -f)

# Make the bridge active on the first boot
- echo "\n\n-------- Applying and attaching network bridge... --------\n"

- netplan apply

# Attach lxdbr0 bridge to LXD default profile
- lxc network attach-profile lxdbr0 default

# Fetch IPv4 address from the device, setup forwarding and NAT
- echo "\n\n-------- Configuring Port Forwarding and NAT... --------\n"

- sysctl -p /etc/sysctl.d/99-maas-nat.conf
- iptables -t nat -A POSTROUTING -o $INTERFACE -j SNAT --to $IP_ADDRESS

# Persist NAT configuration
- netfilter-persistent save

# Install MAAS now that LXD and networking are configured
- echo "\n\n-------- Installing MAAS... --------\n"

- apt-get update
- apt-get install -y maas

# Initialise MAAS
- echo "\n\n-------- Initializing MAAS... --------\n"

- maas init --admin-username $ADMIN_USER --admin-password $ADMIN_PASS --admin-email $ADMIN_EMAIL --admin-ssh-import $SSH_KEY --rbac-url "" --candid-agent-file ""

# Wait for MAAS services to be ready
- |
  echo "\n\n-------- Waiting for MAAS API to be ready... --------\n"
  
  until maas login $ADMIN_USER 'http://localhost:5240/MAAS/' $(maas apikey --username $ADMIN_USER) > /dev/null 2>&1; do
    echo "MAAS is not ready yet (502). Retrying in 30 seconds..."
    sleep 30
  done

# Grab API key and login as admin
- echo "\n\n-------- Logging in as admin user... --------\n"

- export APIKEY=$(maas apikey --username $ADMIN_USER)
- maas login $ADMIN_USER 'http://localhost:5240/MAAS/' $APIKEY

- maas $ADMIN_USER maas set-config name=maas_name value=$MAAS_PROJECT_NAME name=completed_intro value=true

# Automatically create and add ssh keys to MAAS
- echo "\n\n-------- Generating SSH keys and adding them to MAAS... --------\n"

- ssh-keygen -q -t rsa -N "" -f "/home/ubuntu/.ssh/id_rsa"
- chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa /home/ubuntu/.ssh/id_rsa.pub
- chmod 600 /home/ubuntu/.ssh/id_rsa
- chmod 644 /home/ubuntu/.ssh/id_rsa.pub
- maas $ADMIN_USER sshkeys create key="$(cat /home/ubuntu/.ssh/id_rsa.pub)"

# Configure MAAS networking (set gateways, vlans, DHCP on etc)
- echo "\n\n-------- Configuring MAAS networking... --------\n"

- export FABRIC_ID=$(maas $ADMIN_USER subnet read "$SUBNET" | jq -r ".vlan.fabric_id")
- export VLAN_TAG=$(maas $ADMIN_USER subnet read "$SUBNET" | jq -r ".vlan.vid")
- export PRIMARY_RACK=$(maas $ADMIN_USER rack-controllers read | jq -r ".[] | .system_id")

- maas $ADMIN_USER subnet update $SUBNET gateway_ip=$GATEWAY
- maas $ADMIN_USER ipranges create type=dynamic start_ip=$MAAS_RESERVED_IP_START end_ip=$MAAS_RESERVED_IP_END
- maas $ADMIN_USER vlan update $FABRIC_ID $VLAN_TAG dhcp_on=true primary_rack=$PRIMARY_RACK
- maas $ADMIN_USER maas set-config name=upstream_dns value=$MAAS_DNS

# Configure boot images
- echo "\n\n-------- Configuring MAAS boot images... --------\n"

- export BOOT_SOURCE_ID=$(maas $ADMIN_USER boot-sources read | jq -r '.[0].id')

- maas $ADMIN_USER boot-source-selections create $BOOT_SOURCE_ID os="ubuntu" release="noble" arches="amd64" labels='*' subarches='*'
- maas $ADMIN_USER boot-source-selections create $BOOT_SOURCE_ID os="ubuntu" release="jammy" arches="amd64" labels='*' subarches='*'

- maas $ADMIN_USER boot-resources import

# Wait for MAAS boot images to be ready
- |
  echo "\n\n-------- Waiting for all MAAS Boot Images to sync... --------\n"
  
  while true; do
    
    missing_images=false

    importing_status=$(maas $ADMIN_USER boot-resources is-importing)

    # Get the list of images we requested (e.g., "focal jammy noble")
    requested_releases=$(maas $ADMIN_USER boot-source-selections read $BOOT_SOURCE_ID | jq -r '.[].release')

    # Get the list of images that are actually downloaded and ready
    downloaded_releases=$(maas $ADMIN_USER boot-resources read | jq -r '.[].name' | sort | uniq)

    # Check if the image has been downloaded
    for release in $requested_releases; do
      if echo "$downloaded_releases" | grep -q "$release"; then
         # Image exists. Now check if import is finished
         if [ "$importing_status" = "false" ]; then
             echo "  Image '$release' has downloaded!"
         else
             echo "  Image '$release' is currently syncing..."
             missing_images=true
         fi
      else
         echo "  Image '$release' was not found in boot resources..."
         missing_images=true
      fi
    done

    # Check for missing images
    if [ "$missing_images" = "false" ]; then
      clean_list=$(echo "$requested_releases" | tr '\n' ' ')
      echo "All selected boot images ( $clean_list) are fully synced!"
      break
    fi

    # Wait 30 seconds before checking again
    echo "Some images are missing. Waiting 30s..."
    sleep 30
  done

# Generate trust certificate for LXD
- echo "\n\n-------- Generating trust certificate for LXD... --------\n"

- openssl req -x509 -newkey rsa:2048 -keyout $LXD_KEY -out $LXD_CERT -nodes -days 3650 -subj "/CN=lxd-local"

# Trusting generated certificate in LXD
- echo "\n\n-------- Trusting generated certificate in LXD... --------\n"

- lxc config trust add $LXD_CERT --name lxd-local

# Add LXD as a VM host for MAAS
- echo "\n\n-------- Adding LXD as VM host in MAAS... --------\n"

- maas $ADMIN_USER vm-hosts create type=lxd power_address=https://${IP_ADDRESS}:8444 certificate="$(cat $LXD_CERT)" key="$(cat $LXD_KEY)" name=LXD project=$MAAS_PROJECT_NAME
- export VM_HOST_ID=$(maas $ADMIN_USER vm-hosts read | jq -r '.[0].id')

# Compose VMs using VM host (-c limits.cpu=13 -c limits.memory=36GiB --device root,size=150GiB)
- echo "\n\n-------- Composing VM(s) using LXD... --------\n"

- export SYSTEM_ID_1=$(maas $ADMIN_USER vm-host compose $VM_HOST_ID cores=$JUJU_CONTROLLER_CPU memory=$JUJU_CONTROLLER_RAM storage=$JUJU_CONTROLLER_DISK hostname=controller | jq -r '.system_id') && echo $SYSTEM_ID_1

- export SYSTEM_ID_2=$(maas $ADMIN_USER vm-host compose $VM_HOST_ID cores=$NODE_CPU memory=$NODE_RAM storage=$NODE_MAIN_DISK hostname=node1 | jq -r '.system_id') && echo $SYSTEM_ID_2

- export SYSTEM_ID_3=$(maas $ADMIN_USER vm-host compose $VM_HOST_ID cores=$NODE_CPU memory=$NODE_RAM storage=$NODE_MAIN_DISK hostname=node2 | jq -r '.system_id') && echo $SYSTEM_ID_3

- export SYSTEM_ID_4=$(maas $ADMIN_USER vm-host compose $VM_HOST_ID cores=$NODE_CPU memory=$NODE_RAM storage=$NODE_MAIN_DISK hostname=node3 | jq -r '.system_id') && echo $SYSTEM_ID_4

- export SYSTEM_ID_5=$(maas $ADMIN_USER vm-host compose $VM_HOST_ID cores=$CLIENT_CPU memory=$CLIENT_RAM storage=$CLIENT_MAIN_DISK hostname=client | jq -r '.system_id') && echo $SYSTEM_ID_5

# Wait for VMs to be ready
- |
  echo "\n\n-------- Waiting for VMs to enter 'Ready' state... --------\n"
  
  IDS=$(maas $ADMIN_USER machines read | jq -r --arg host_id "$VM_HOST_ID" '.[] | select(.pod.id == ($host_id | tonumber)) | .system_id')
  
  # Safety check: Ensure we actually have IDs to check
  if [ -z "$IDS" ]; then
    echo "Error: No VMs found belonging to Host ID '$VM_HOST_ID'."
    exit 1
  fi

  # Start the loop
  while true; do
    all_ready=true
    
    for id in $IDS; do
      # Query MAAS for the status name
      status=$(maas $ADMIN_USER machine read "$id" | jq -r '.status_name')
      echo "  Machine '$id' is currently '$status'..."
      # If any machine is NOT ready, we mark the flag as false
      if [ "$status" != "Ready" ]; then
         all_ready=false
      fi
    done

    # If the flag is still true, everyone is ready -> break the loop
    if [ "$all_ready" = true ]; then
      echo "All VMs are Ready!"
      break
    fi

    # Wait 60 seconds before checking again
    echo "Waiting 60s before checking again..."
    sleep 60
  done

# Create tags and add them to commissioned machines
- echo "\n\n-------- Creating and adding Tags... --------\n"

- maas $ADMIN_USER tags create name=juju
- maas $ADMIN_USER tag update-nodes juju add=$SYSTEM_ID_1

- maas $ADMIN_USER tags create name=client
- maas $ADMIN_USER tag update-nodes client add=$SYSTEM_ID_5

# Create MAAS Juju Cloud configuration files
- echo "\n\n-------- Creating MAAS Juju Cloud Configs... --------\n"

- |
  cat <<EOF > /home/ubuntu/maas-cloud.yaml
  clouds:
    maas:
      type: maas
      auth-types: [oauth1]
      endpoint: http://${IP_ADDRESS}:5240/MAAS
  EOF

- |
  cat <<EOF > /home/ubuntu/maas-creds.yaml
  credentials:
    maas:
      anyuser:
        auth-type: oauth1
        maas-oauth: $APIKEY
  EOF

- chown ubuntu:ubuntu /home/ubuntu/maas-*.yaml

# Add MAAS as a Juju Cloud
- echo "\n\n-------- Adding MAAS as a Juju Cloud... --------\n"

- su ubuntu -c 'juju add-cloud --client -f ~/maas-cloud.yaml maas'

# Add MAAS as a Juju Cloud
- echo "\n\n-------- Adding MAAS Credentials to Juju... --------\n"

- su ubuntu -c 'juju add-credential --client -f ~/maas-creds.yaml maas'

# Remove config files
- rm /home/ubuntu/maas-*.yaml

# Bootstrap Juju controller
- echo "\n\n-------- Bootstrapping Juju Controller... --------\n"

- su ubuntu -c 'juju bootstrap --bootstrap-base=ubuntu@22.04 --constraints tags=juju maas juju-controller'


# -------------------------------------------- DEPLOY CHARMED HA LANDSCAPE --------------------------------------------


# Create Juju Model
- echo "\n\n-------- Creating Juju Landscape Model... --------\n"

- su ubuntu -c 'juju add-model --config default-base=ubuntu@22.04 landscape-dense-maas'

# ------------------------------------------------- Deploy Machines -------------------------------------------------
- echo "\n\n-------- Deploying Juju Machines... --------\n"

- su ubuntu -c 'juju add-machine -n 3 --constraints "mem=8192 cores=3 root-disk=30G"'
- su ubuntu -c 'juju add-machine --constraints tags=client'

# Wait for machines to be started so LXD is ready
- echo "\n\n-------- Waiting for Machines to start... --------\n"

- su ubuntu -c "juju wait-for machine 0 --timeout=20m --query='life==\"alive\" && status==\"started\"'"
- su ubuntu -c "juju wait-for machine 1 --timeout=20m --query='life==\"alive\" && status==\"started\"'"
- su ubuntu -c "juju wait-for machine 2 --timeout=20m --query='life==\"alive\" && status==\"started\"'"
- su ubuntu -c "juju wait-for machine 3 --timeout=20m --query='life==\"alive\" && status==\"started\"'"

# ------------------------------------------------- Deploy HAProxy -------------------------------------------------
- echo "\n\n-------- Deploying HAProxy... --------\n"

- |
  cat <<EOF > /home/ubuntu/haproxy.yaml
  haproxy:
    default_timeouts: "queue 60000, connect 5000, client 120000, server 120000"
    global_default_bind_options: "no-tlsv10"
    ssl_cert: "SELFSIGNED"
    services: ""
  EOF

- chown ubuntu:ubuntu /home/ubuntu/haproxy.yaml

- su ubuntu -c 'juju deploy -n 3 --channel $HAPROXY_VERSION --to lxd:0,lxd:1,lxd:2 --config ~/haproxy.yaml haproxy'

- rm /home/ubuntu/haproxy.yaml

# Expose HAProxy
- su ubuntu -c 'juju expose haproxy'

# Wait for HAProxy to be deployed
- echo "\n\n-------- Waiting for HAProxy... --------\n"

- su ubuntu -c "juju wait-for application haproxy --timeout=20m --query='life==\"alive\" && status==\"active\" && len(units) == 3'"

# ------------------------------------------------- Deploy PostgreSQL -------------------------------------------------
- echo "\n\n-------- Deploying PostgreSQL... --------\n"

- |
  cat <<EOF > /home/ubuntu/postgresql.yaml
  postgresql:
    plugin_plpython3u_enable: true
    plugin_ltree_enable: true
    plugin_intarray_enable: true
    plugin_debversion_enable: true
    plugin_pg_trgm_enable: true
    experimental_max_connections: 500
    memory_max_prepared_transactions: 500
  EOF

- chown ubuntu:ubuntu /home/ubuntu/postgresql.yaml

- su ubuntu -c 'juju deploy -n 3 --channel $POSTGRESQL_VERSION --to 0,1,2 --constraints mem=2048 --config ~/postgresql.yaml postgresql'

- rm /home/ubuntu/postgresql.yaml

# Wait for PostgreSQL to be deployed
- echo "\n\n-------- Waiting for PostgreSQL... --------\n"

- su ubuntu -c "juju wait-for application postgresql --timeout=20m --query='life==\"alive\" && status==\"active\" && len(units) == 3'"

# ----------------------------------------------- Deploy RabbitMQ Server -----------------------------------------------
- echo "\n\n-------- Deploying RabbitMQ... --------\n"

- |
  cat <<EOF > /home/ubuntu/rabbitmq.yaml
  rabbitmq-server:
    consumer-timeout: 259200000
  EOF

- chown ubuntu:ubuntu /home/ubuntu/rabbitmq.yaml

- su ubuntu -c 'juju deploy -n 3 --channel $RABBITMQ_VERSION --to lxd:0,lxd:1,lxd:2 --config ~/rabbitmq.yaml rabbitmq-server'

- rm /home/ubuntu/rabbitmq.yaml

# Wait for RabbitMQ to be deployed
- echo "\n\n-------- Waiting for RabbitMQ... --------\n"

- su ubuntu -c "juju wait-for application rabbitmq-server --timeout=20m --query='life==\"alive\" && status==\"active\" && len(units) == 3'"

# --------------------------------------------- Deploy Landscape Server ---------------------------------------------
- echo "\n\n-------- Deploying Landscape Server... --------\n"

- su ubuntu -c 'juju deploy -n 3 --channel $LANDSCAPE_SERVER_VERSION --to lxd:0,lxd:1,lxd:2 --constraints mem=4096 landscape-server'

# Integrate Landscape Server
- su ubuntu -c 'juju integrate landscape-server rabbitmq-server'
- su ubuntu -c 'juju integrate landscape-server haproxy'
- su ubuntu -c 'juju integrate landscape-server:db postgresql:db-admin'

# Wait for Landscape Server to be deployed
- echo "\n\n-------- Waiting for Landscape Server... --------\n"

- su ubuntu -c "juju wait-for application landscape-server --timeout=20m --query='life==\"alive\" && status==\"active\" && len(units) == 3'"

# --------------------------------------------- Deploy Ubuntu machine ---------------------------------------------
- echo "\n\n-------- Deploying Ubuntu Machine... --------\n"

- su ubuntu -c 'juju deploy --base $CLIENT_BASE --to 3 ubuntu'

# Wait for Ubuntu to be deployed
- echo "\n\n-------- Waiting for Ubuntu Machine... --------\n"

- su ubuntu -c "juju wait-for application ubuntu --timeout=20m --query='life==\"alive\" && status==\"active\"'"

# --------------------------------------------- Deploy Landscape Client ---------------------------------------------
- echo "\n\n-------- Deploying Landscape Client... --------\n"

# Obtain HAProxy IP
- HAPROXY_IP=$(su ubuntu -c 'juju exec --unit haproxy/leader -- unit-get public-address')

- |
  cat <<EOF > /home/ubuntu/landscape-client.yaml
  landscape-client:
    computer-title: "$CLIENT_COMPUTER_NAME"
    account-name: "$CLIENT_ACCOUNT_NAME"
    ping-url: "http://${HAPROXY_IP}/ping"
    url: "https://${HAPROXY_IP}/message-system"
    script-users: 'nobody,landscape,root'
    tags: ''
  EOF

- chown ubuntu:ubuntu /home/ubuntu/landscape-client.yaml

- su ubuntu -c 'juju deploy --channel $LANDSCAPE_CLIENT_VERSION --config ~/landscape-client.yaml landscape-client'

- rm /home/ubuntu/landscape-client.yaml

# Attach Ubuntu Pro Token
- su ubuntu -c "juju ssh landscape-client/leader \"sudo pro attach C12NUyK6MQUgNMLZjR4CDW5KX334gx\""

# Relate Client with Ubuntu Machine
- echo "\n\n-------- Attaching Landscape Client to Ubuntu Machine... --------\n"

- su ubuntu -c 'juju relate landscape-client ubuntu'

# Register Landscape client
- echo "\n\n-------- Registering Landscape Client to Server... --------\n"

- su ubuntu -c 'juju run landscape-client/leader register'

# Wait for Landscape to be deployed
- echo "\n\n-------- Waiting for Landscape Client... --------\n"

- su ubuntu -c "juju wait-for application landscape-client --timeout=20m --query='life==\"alive\"'"


- echo "\n\n-------- Finished deploying Charmed Landscape HA on-prem, have fun! --------\n"

